server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE

  config:
    import: optiona;:configserver://localhost:8085
  profiles:
    active: prod

  data:
    mongoDb:
      uri: mongodb://localhost/27017
      database: rating_microservice