server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  config:
    import: optiona;:configserver://localhost:8085
  profiles:
    active: prod

  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/users/**

          - id: ANIME-SERVICE
            uri: lb://ANIME-SERVICE
            predicates:
              - Path=/animes/**

          - id: RATING-SERVICE
            uri: lb://RATING-SERVICE
            predicates:
              - Path=/ratings/**

          - id: CONFIG-SERVER
            uri: lb://CONFIG-SERVER
            predicates:
              - Path=/application/**

